name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      NODE_VERSION: 20

    steps:
      - uses: actions/checkout
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup

      - name: Setup Node.js
        uses: actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist